### ISSUE TITLE
Typing error in bluetoothScanner.py

### ISSUE THREAD

**Issue by FoxRomeo** [rkoshak/sensorReporter#50]
Line 164:
        for conn in self.publisher:

should be
        for conn in self.publish:

Error message:
bash-4.4# python /opt/sensorReporter/sensorReporter.py /opt/sensorReporter/sensorReporter.ini
Starting...
Loading /opt/sensorReporter/sensorReporter.ini
Configuring logger: file = /var/log/mqttReporter.log size = 67108864 num = 10
Traceback (most recent call last):
  File "/opt/sensorReporter/sensorReporter.py", line 207, in <module>
    main()
  File "/opt/sensorReporter/sensorReporter.py", line 71, in main
    loadConfig(sys.argv[1])
  File "/opt/sensorReporter/sensorReporter.py", line 199, in loadConfig
    sensors[section] = createDevice(config, section)
  File "/opt/sensorReporter/sensorReporter.py", line 158, in createDevice
    d = MyDevice(devConns, logger, params, sensors, actuators)
  File "/opt/sensorReporter/bluetoothScanner.py", line 62, in __init__
    self.publishState()
  File "/opt/sensorReporter/bluetoothScanner.py", line 164, in publishState
    for conn in self.publisher:

**Comment by rkoshak** [comment]
Thanks for the report. I've corrected the code.
